"""Publish the model to the Hugging Face Hub — personal account only.

This project is personally funded and personally owned. Everything here is
arranged so an accidental push to an organisation namespace fails loudly rather
than silently costing someone else money or attributing the work to them:

  * the authenticated user must be exactly PERSONAL_ACCOUNT,
  * the target repo id must sit under PERSONAL_ACCOUNT/,
  * no `organization=` or `bill_to=` argument is ever passed,
  * membership of any org is irrelevant and never consulted.

It also refuses to upload anything that looks like essay text: the source corpus
is copyright-restricted, so only weights, tokenizer files and the model card go up.

Usage:
    python scripts/publish.py --dry-run     # show exactly what would be uploaded
    python scripts/publish.py               # do it
"""
import argparse
import re
import sys
from pathlib import Path

PERSONAL_ACCOUNT = "akagabi"
REPO_ID = f"{PERSONAL_ACCOUNT}/enemBERT"
GITHUB = "https://github.com/akagabi/enembert/blob/main"

MODEL_DIR = Path("runs/model/final")
ONNX_DIR = Path("runs/model/onnx")

# torch weights + tokenizer (what `from_pretrained` needs), and the int8 ONNX
# (what the browser streams). The fp32 ONNX is a parity-check reference only and
# is regenerated by scripts/export_onnx.py, so it is deliberately not uploaded.
MODEL_FILES = ["config.json", "model.safetensors", "special_tokens_map.json",
               "tokenizer_config.json", "tokenizer.json", "vocab.txt"]
ONNX_FILES = ["model_quantized.onnx"]


class PublishGuardError(RuntimeError):
    """Raised when a safety precondition for publishing is not met."""


def assert_personal_account(api) -> str:
    """The authenticated identity must be the personal account, exactly."""
    who = api.whoami()
    name = who.get("name")
    if name != PERSONAL_ACCOUNT:
        raise PublishGuardError(
            f"authenticated as {name!r}, expected {PERSONAL_ACCOUNT!r}. "
            f"Log in with the personal token: `hf auth login`.")
    if not REPO_ID.startswith(f"{PERSONAL_ACCOUNT}/"):
        raise PublishGuardError(f"{REPO_ID!r} is not under {PERSONAL_ACCOUNT}/")
    return name


def assert_no_essay_text(paths: list[Path]) -> None:
    """Tripwire against shipping corpus text inside a model repo."""
    for p in paths:
        if p.suffix in {".json", ".txt", ".md"} and p.stat().st_size < 5_000_000:
            head = p.read_text(errors="ignore")[:200_000]
            # Corpus essays are long prose; tokenizer/vocab files are not.
            if re.search(r"[A-Za-zÀ-ÿ,;: ]{400,}", head) and p.name != "README.md":
                raise PublishGuardError(
                    f"{p} contains long prose and may hold essay text — refusing to upload")


def model_card() -> str:
    """The repo's MODEL_CARD with relative links made absolute.

    Relative links resolve on GitHub but 404 on the Hub, where the card is
    rendered at the root of a different repo.
    """
    card = Path("MODEL_CARD.md").read_text()
    card = re.sub(r"\]\(\./([^)]+)\)", rf"]({GITHUB}/\1)", card)
    if "](./" in card:
        raise PublishGuardError("a relative link survived rewriting; it would 404 on the Hub")
    return card


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="print the plan, upload nothing")
    a = ap.parse_args()

    from huggingface_hub import HfApi

    api = HfApi()
    who = assert_personal_account(api)

    uploads: list[tuple[Path, str]] = []
    for f in MODEL_FILES:
        uploads.append((MODEL_DIR / f, f))
    for f in ONNX_FILES:
        uploads.append((ONNX_DIR / f, f"onnx/{f}"))
    # transformers.js looks for the tokenizer next to the ONNX subfolder too.
    for f in ("config.json", "tokenizer.json", "tokenizer_config.json", "special_tokens_map.json"):
        uploads.append((ONNX_DIR / f, f"onnx/{f}"))

    missing = [str(src) for src, _ in uploads if not src.exists()]
    if missing:
        raise PublishGuardError(f"missing files: {missing}. Run training and scripts/export_onnx.py first.")
    assert_no_essay_text([src for src, _ in uploads])

    total = sum(src.stat().st_size for src, _ in uploads)
    print(f"authenticated as : {who}  (personal account verified)")
    print(f"target repo      : {REPO_ID}   [public]")
    print(f"payload          : {len(uploads)} files, {total / 1e6:.0f} MB")
    for src, dst in uploads:
        print(f"    {src.stat().st_size / 1e6:8.1f} MB  {src}  ->  {dst}")
    print(f"    {len(model_card()) / 1e3:8.1f} kB  MODEL_CARD.md (links absolutised)  ->  README.md")

    if a.dry_run:
        print("\n--dry-run: nothing uploaded.")
        return 0

    # No `organization=`, no `bill_to=`: the repo id alone determines the namespace.
    api.create_repo(REPO_ID, repo_type="model", private=False, exist_ok=True)
    for src, dst in uploads:
        print(f"uploading {dst} ...", flush=True)
        api.upload_file(path_or_fileobj=str(src), path_in_repo=dst,
                        repo_id=REPO_ID, repo_type="model")
    api.upload_file(path_or_fileobj=model_card().encode(), path_in_repo="README.md",
                    repo_id=REPO_ID, repo_type="model")
    print(f"\ndone: https://huggingface.co/{REPO_ID}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PublishGuardError as e:
        print(f"REFUSED: {e}", file=sys.stderr)
        sys.exit(2)
